"""莆仙话中文词库数据"""
CHINESE_WORDS = [
    # === Level 1: 基础词 (HSK 1-2) ===
    ("你", "pronoun", 1), ("我", "pronoun", 1), ("他", "pronoun", 1), ("她", "pronoun", 1),
    ("我们", "pronoun", 1), ("你们", "pronoun", 1), ("他们", "pronoun", 1),
    ("好", "adj", 1), ("不好", "adj", 1), ("大", "adj", 1), ("小", "adj", 1),
    ("多", "adj", 1), ("少", "adj", 1), ("长", "adj", 1), ("短", "adj", 1),
    ("高", "adj", 1), ("矮", "adj", 1), ("胖", "adj", 1), ("瘦", "adj", 1),
    ("冷", "adj", 1), ("热", "adj", 1), ("忙", "adj", 1), ("累", "adj", 1),
    ("开心", "emotion", 1), ("难过", "emotion", 1), ("生气", "emotion", 1),
    ("害怕", "emotion", 1), ("喜欢", "emotion", 1), ("爱", "emotion", 1),
    ("是", "verb", 1), ("不是", "verb", 1), ("有", "verb", 1), ("没有", "verb", 1),
    ("来", "verb", 1), ("去", "verb", 1), ("走", "verb", 1), ("跑", "verb", 1),
    ("吃", "verb", 1), ("喝", "verb", 1), ("说", "verb", 1), ("看", "verb", 1),
    ("听", "verb", 1), ("做", "verb", 1), ("买", "verb", 1), ("卖", "verb", 1),
    ("知道", "verb", 1), ("想要", "verb", 1), ("可以", "verb", 1),
    ("今天", "time", 1), ("明天", "time", 1), ("昨天", "time", 1),
    ("早上", "time", 1), ("中午", "time", 1), ("晚上", "time", 1),
    ("现在", "time", 1), ("几点", "time", 1), ("什么时候", "time", 1),
    ("一", "num", 1), ("二", "num", 1), ("三", "num", 1), ("四", "num", 1),
    ("五", "num", 1), ("六", "num", 1), ("七", "num", 1), ("八", "num", 1),
    ("九", "num", 1), ("十", "num", 1), ("百", "num", 1),
    ("多少钱", "question", 1), ("哪里", "question", 1), ("什么", "question", 1),
    ("为什么", "question", 1), ("怎么", "question", 1), ("谁", "question", 1),
    ("是不是", "question", 1), ("有没有", "question", 1),

    # === Level 2: 日常词汇 ===
    ("吃饭", "daily", 2), ("喝水", "daily", 2), ("睡觉", "daily", 2),
    ("起床", "daily", 2), ("上班", "daily", 2), ("下班", "daily", 2),
    ("回家", "daily", 2), ("出门", "daily", 2), ("洗澡", "daily", 2),
    ("穿衣服", "daily", 2), ("脱衣服", "daily", 2), ("做饭", "daily", 2),
    ("洗碗", "daily", 2), ("扫地", "daily", 2), ("洗衣服", "daily", 2),
    ("喝茶", "daily", 2), ("喝水", "daily", 2), ("抽烟", "daily", 2),
    ("谢谢", "daily", 2), ("对不起", "daily", 2), ("没关系", "daily", 2),
    ("你好", "daily", 2), ("再见", "daily", 2), ("欢迎", "daily", 2),
    ("恭喜", "daily", 2), ("辛苦了", "daily", 2), ("麻烦你了", "daily", 2),
    ("要", "verb", 2), ("不要", "verb", 2), ("想", "verb", 2), ("会", "verb", 2),
    ("不会", "verb", 2), ("能", "verb", 2), ("不能", "verb", 2),
    ("快", "adj", 2), ("慢", "adj", 2), ("新", "adj", 2), ("旧", "adj", 2),
    ("好喝", "adj", 2), ("好吃", "adj", 2), ("好看", "adj", 2), ("好听", "adj", 2),
    ("漂亮", "adj", 2), ("难看", "adj", 2), ("聪明", "adj", 2), ("笨", "adj", 2),
    ("干净", "adj", 2), ("脏", "adj", 2), ("贵", "adj", 2), ("便宜", "adj", 2),
    ("远", "adj", 2), ("近", "adj", 2),

    # === Level 3: 场景词汇 ===
    ("家", "place", 3), ("学校", "place", 3), ("医院", "place", 3),
    ("超市", "place", 3), ("市场", "place", 3), ("饭馆", "place", 3),
    ("公司", "place", 3), ("公园", "place", 3), ("车站", "place", 3),
    ("厕所", "place", 3), ("楼上", "place", 3), ("楼下", "place", 3),
    ("里面", "place", 3), ("外面", "place", 3), ("前面", "place", 3),
    ("后面", "place", 3), ("左边", "place", 3), ("右边", "place", 3),
    ("饭", "food", 3), ("菜", "food", 3), ("肉", "food", 3), ("鱼", "food", 3),
    ("鸡", "food", 3), ("鸭", "food", 3), ("蛋", "food", 3), ("面", "food", 3),
    ("粥", "food", 3), ("饭", "food", 3), ("汤", "food", 3), ("水果", "food", 3),
    ("茶", "food", 3), ("咖啡", "food", 3), ("牛奶", "food", 3), ("酒", "food", 3),
    ("书", "object", 3), ("笔", "object", 3), ("纸", "object", 3),
    ("手机", "object", 3), ("电脑", "object", 3), ("电视", "object", 3),
    ("桌子", "object", 3), ("椅子", "object", 3), ("床", "object", 3),
    ("门", "object", 3), ("窗", "object", 3), ("灯", "object", 3),
    ("衣服", "object", 3), ("裤子", "object", 3), ("鞋子", "object", 3),
    ("钱", "object", 3), ("钥匙", "object", 3), ("伞", "object", 3),
    ("钱包", "object", 3), ("背包", "object", 3), ("眼镜", "object", 3),

    # === Level 4: 句子 ===
    ("你好吗", "sentence", 4), ("我很好", "sentence", 4),
    ("你叫什么名字", "sentence", 4), ("我叫...", "sentence", 4),
    ("很高兴认识你", "sentence", 4), ("你从哪里来", "sentence", 4),
    ("我从...来", "sentence", 4), ("你住在哪里", "sentence", 4),
    ("我住在...", "sentence", 4), ("你做什么工作", "sentence", 4),
    ("我是...", "sentence", 4), ("你吃饭了吗", "sentence", 4),
    ("我吃饭了", "sentence", 4), ("你要去哪里", "sentence", 4),
    ("我要去...", "sentence", 4), ("这个多少钱", "sentence", 4),
    ("太贵了", "sentence", 4), ("便宜一点", "sentence", 4),
    ("我喜欢你", "sentence", 4), ("我想你", "sentence", 4),
    ("好久不见", "sentence", 4), ("明天见", "sentence", 4),
    ("今天天气真好", "sentence", 4), ("下雨了", "sentence", 4),
    ("天冷了", "sentence", 4), ("天热了", "sentence", 4),
    ("请坐", "sentence", 4), ("请喝茶", "sentence", 4),
    ("慢走", "sentence", 4), ("一路平安", "sentence", 4),
    ("生日快乐", "sentence", 4), ("新年快乐", "sentence", 4),
    ("恭喜发财", "sentence", 4), ("身体健康", "sentence", 4),
    ("我不知道", "sentence", 4), ("我不明白", "sentence", 4),
    ("请再说一遍", "sentence", 4), ("说慢一点", "sentence", 4),
    ("可以帮我吗", "sentence", 4), ("没问题", "sentence", 4),
]

CAT_NAMES = {
    "pronoun": "人称代词", "adj": "形容词", "emotion": "情感",
    "verb": "动词", "time": "时间", "num": "数字",
    "question": "疑问词", "daily": "日常用语", "place": "地点",
    "food": "饮食", "object": "物品", "sentence": "常用句子",
}
